name = "sweet-river-9262"
main = "index.js"
compatibility_date = "2024-01-01"

workers_dev = true

[build]
command = ""

# Binding สำหรับ Environment Variables (placeholder)
# Cloudflare จะ override ด้วย Secrets ที่คุณเพิ่มไว้บน Dashboard
[vars]
LINE_CAREGIVER_ID = ""
LINE_CHANNEL_ACCESS_TOKEN = ""
WORKER_SECRET_KEY = ""

[observability]
enabled = true
